<!-- BEGIN COLORBOX <?php print $box_id . '-' . $box_class; ?>-->
<div id="<?php print $box_id; ?>" class="color-box <?php print $box_class; ?>" <?php print $box_width; ?>>
	<div class="border-top"> <div class="border-top-right"></div> </div>
	<div class="content">
		<?php print $box_title ?>
		<?php print $box_content?>
	</div>
	<div class="border-bottom"> <div class="border-bottom-right"></div> </div>
</div>
<!-- END COLORBOX <?php print $box_id . '-' . $box_class; ?>-->