	<!--[if IE]><link rel="stylesheet" type="text/css" href="<?print $_CMAPP['css_url']; ?>/ie_css_fixes.css" /><![endif]-->
	<div id="header">
		<div class="peca-logo"></div>
		<div class="amadis-logo"></div>
		<div class="menu">
			<?php print $main_menu; ?>
		</div>
	</div>
	<div id="global-wrapper">
		<div id="side-bar">
			<?=$side_bar?>
		</div>
		
		<div id="container">		
			<div id="center" class="column">
				<?php print $section_title; ?>
				<?php print $notices; ?>
				<?php print $main_content ?>
			</div>
	</div>
	<div id="footer"><?php print $_language['amadis']; ?></div>
</div>
<div id="footer-wrapper"></div>