<div id="loginInit">
	<div id="loginInitTopBorder"></div>
	<div id="loginInitContent">
		<div id="loginInitContentImage"><?php print $login_status; ?></div>
		<div style="padding-left: 10px;">
			<?php print $loginbox_content; ?>
		</div>
	</div>
	<div id="loginInitBottomBorder"></div>
</div>

<?php if($_SESSION['environment']->logged) : ?>
<div id="menubox">
	<div id="menuTop">
		<div id="imageTop"></div>
		<div id="my"><?php print $_language['my_amadis']; ?></div>
	</div>
	<div id="menu">
		<ul>
			<li class="webfolio_txt<?php print $webfolio_active ?>">
				<a href="<?php print $_CMAPP['services_url'];?>/webfolio/webfolio.php"><?php print $_language['webfolio']; ?></a>
			</li>
			<li class="blog_txt<?php print $blog_active; ?>">
				<a href="<?php print $_CMAPP['services_url']; ?>/blog/blog.php"><?php print $_language['blog']; ?></a>
			</li>
			<li class="lib_txt<?php print $library_active; ?>">
				<a href="<?php print $_CMAPP["services_url"]; ?>/library/biblioteca.php"><?php print $_language['library']; ?></a>
			</li>
			<?php print $friends_list; ?>
			<?php print $projects_list; ?>
			<?php print $communities_list; ?>
		</ul>
	</div>
	<div id="menuBottom"></div>
</div>
<?php else : ?>
<div class="menu-box" style="margin-top: 20px;">
	<div class="border-top"></div>
	<div class="content">
		<a href="<?=$_CMAPP['services_url']?>/webfolio/recoverpassword.php"><img src="<?=$_CMAPP['imlang_url']?>/img_esqueci.gif" alt="" /></a>
	</div>
	<div class="border-bottom"></div>
	</div>
<?php endif; ?>
