			<div id="menubox">
				<div id="menuTop">
					<div id="imageTop"></div>
					<div id="my">Meu Amadis</div>
				</div>
				<div id="menu">
					<ul>
						<li class="webfolio_txt"><a href="#">Webfólio</a></li>
						<li class="blog_txt"><a href="#">Diário</a></li>
						<li class="lib_txt"><a href="#">Arquivos</a></li>
						<li class="friends_txt"><a href="javascript:void(0);" onclick="openCloseSubMenu(document.getElementById('friendSubMenu'));">Amigos</a>
							<ul id="friendSubMenu" style="">
								<li>&raquo; Felisberto</li>
								<li>&raquo; Alevino</li>
							</ul>
						</li>
						<li class="project_txt"><a href="javascript:void(0);" onclick="openCloseSubMenu(document.getElementById('projectSubMenu'));">Projetos</a>
							<ul id="projectSubMenu" style="">
								<!-- display:none -->
								<li>&raquo; Lego</li>
								<li>&raquo; Teste Maléfico</li>
							</ul>
						</li>
						<li  class="communities_txt"><a href="javascript:void(0);" onclick="openCloseSubMenu(document.getElementById('comunitiesSubMenu'));">Comunidades</a>
							<ul id="comunitiesSubMenu" style="">
								<li>&raquo; Meu Cachorrinho</li>
								<li>&raquo; Alevinos da farra</li>
							</ul>		
						</li>
					</ul>	
				</div>
				<div id="menuBottom"></div>
			</div>
